<?php

namespace BHM\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoRepository extends EntityRepository
{
}
