

bhm_core_login:
    path:     /
    defaults: { _controller: BHMCoreBundle:Default:dashboard }

bhm_core_dashboard:
    path:     /dashboard
    defaults: { _controller: BHMCoreBundle:Default:dashboard }
